const defaultProducts=[
 {id:1,name:'Pawfect Adult Dog Food',category:'Pet Food',price:1450,old:1650,emoji:'🐶',image:'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=700&q=80',stock:24,brand:'Pawfect',weight:'3 kg',tag:'Best seller',desc:'Balanced chicken and rice nutrition for energetic adult dogs.'},
 {id:2,name:'Whisker Care Cat Food',category:'Pet Food',price:980,emoji:'🐱',image:'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=700&q=80',stock:18,brand:'Whisker Care',weight:'1.2 kg',tag:'New',desc:'Complete ocean-fish recipe made for healthy, happy cats.'},
 {id:3,name:'Organic Tomato Seeds',category:'Plant Seeds',price:120,emoji:'🍅',image:'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=700&q=80',stock:42,brand:'GreenPaws Grow',weight:'20 seeds',tag:'Popular',desc:'Sweet, productive tomatoes for sunny balconies and gardens.'},
 {id:4,name:'Kitchen Herb Garden Kit',category:'Plant Seeds',price:350,emoji:'🌿',image:'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=700&q=80',stock:8,brand:'GreenPaws Grow',weight:'5 varieties',tag:'New',desc:'Basil, coriander, mint, parsley and chilli in one easy kit.'},
 {id:5,name:'Sunflower Seed Pack',category:'Plant Seeds',price:150,emoji:'🌻',image:'https://images.unsplash.com/photo-1470509037663-253afd7f0f51?auto=format&fit=crop&w=700&q=80',stock:31,brand:'GreenPaws Grow',weight:'15 seeds',desc:'Cheerful giant sunflowers that are simple to grow.'},
 {id:6,name:'Natural Pet Treats',category:'Accessories',price:420,emoji:'🦴',image:'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=700&q=80',stock:13,brand:'Pawfect',weight:'250 g',desc:'Crunchy, wholesome treats with no artificial flavours.'},
 {id:7,name:'Premium Cat Litter',category:'Accessories',price:750,emoji:'🐾',image:'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=700&q=80',stock:5,brand:'Whisker Care',weight:'5 L',tag:'Low stock',desc:'Fast-clumping and odour-control litter for a clean home.'},
 {id:8,name:'Butterfly Flower Mix',category:'Plant Seeds',price:220,emoji:'🌼',image:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=700&q=80',stock:29,brand:'GreenPaws Grow',weight:'30 seeds',desc:'A colourful mix that welcomes butterflies to your garden.'}
];
let products=defaultProducts;
let cart=JSON.parse(localStorage.getItem('gpCart')||'[]'),coupon=localStorage.getItem('gpCoupon')||'',search='',category='All',sort='featured';
const taka=n=>'৳'+n.toLocaleString('en-US');
function track(event,detail={}){fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,detail})}).catch(()=>{});}
function save(){localStorage.setItem('gpCart',JSON.stringify(cart));localStorage.setItem('gpCoupon',coupon);renderCart();}
function renderProducts(){let list=products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase()));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);document.querySelector('#products').innerHTML=list.map(p=>`<article class="product"><div class="product-img" onclick="showProduct(${p.id})">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:`<span>${p.emoji}</span>`}</div>${p.tag?`<span class="badge">${p.tag}</span>`:''}<button class="quick-add" onclick="addToCart(${p.id})" aria-label="Add ${p.name}">+</button><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><span class="price">${taka(p.price)}</span>${p.old?`<span class="old-price">${taka(p.old)}</span>`:''}</div></article>`).join('')||'<p>No products match your search.</p>';}
function addToCart(id){let line=cart.find(x=>x.id===id);if(line)line.qty++;else cart.push({id,qty:1});track('add_to_cart',{id});save();toast('Added to your cart');}
function renderCart(){const totalItems=cart.reduce((n,x)=>n+x.qty,0);document.querySelector('#cartCount').textContent=totalItems;document.querySelector('#mobileCartCount').textContent=totalItems;let subtotal=cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0),discount=coupon==='GREEN10'?Math.round(subtotal*.1):0,shipping=subtotal-discount>=1500||!subtotal?0:80;document.querySelector('#cartItems').innerHTML=cart.length?cart.map(x=>{let p=products.find(p=>p.id===x.id);return `<div class="cart-line"><span class="emoji">${p.emoji}</span><div><b>${p.name}</b><span>${taka(p.price)}</span><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button> ${x.qty} <button onclick="changeQty(${p.id},1)">+</button></div></div><button class="remove" onclick="removeItem(${p.id})">×</button></div>`}).join(''):'<p>Your cart is waiting for something lovely.</p>';document.querySelector('#cartSummary').innerHTML=`<div class="summary"><div><span>Subtotal</span><span>${taka(subtotal)}</span></div><div><span>Discount</span><span>−${taka(discount)}</span></div><div><span>Shipping</span><span>${shipping?'৳80':'Free'}</span></div><div class="total"><span>Total</span><span>${taka(subtotal-discount+shipping)}</span></div></div>`;}
function changeQty(id,d){let x=cart.find(x=>x.id===id);x.qty+=d;if(x.qty<1)cart=cart.filter(x=>x.id!==id);save();}function removeItem(id){cart=cart.filter(x=>x.id!==id);track('remove_from_cart',{id});save();}
function showProduct(id){let p=products.find(p=>p.id===id);track('product_view',{id});document.querySelector('#productContent').innerHTML=`<div class="detail"><div class="large-emoji">${p.image?`<img src="${p.image}" alt="${p.name}">`:p.emoji}</div><div><small>${p.category} · ${p.brand}</small><h2>${p.name}</h2><b class="price">${taka(p.price)}</b><p>${p.desc}</p><p><b>Weight:</b> ${p.weight} &nbsp; <b>SKU:</b> GP-${String(p.id).padStart(4,'0')}<br><b>Availability:</b> ${p.stock?'In stock ('+p.stock+')':'Out of stock'}</p><button class="btn" onclick="addToCart(${p.id});document.querySelector('#productModal').close()">Add to cart</button></div></div>`;document.querySelector('#productModal').showModal();}
function showCheckout(){if(!cart.length)return toast('Your cart is empty');track('checkout_started');let total=cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0);document.querySelector('#checkoutContent').innerHTML=`<div class="checkout-box"><h2>Checkout</h2><p>Order total: <b>${taka(total)}</b></p><form id="checkoutForm"><input required name="name" placeholder="Full name"><input required name="phone" placeholder="Mobile number"><input class="wide" required name="address" placeholder="Delivery address"><input required name="email" type="email" placeholder="Email address"><select name="payment"><option>Cash on Delivery</option><option>bKash (Demo)</option><option>Nagad (Demo)</option><option>SSLCommerz (Demo)</option></select><button class="btn wide">Place order →</button></form></div>`;document.querySelector('#checkoutModal').showModal();document.querySelector('#checkoutForm').onsubmit=async e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));try{let r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,items:cart})}),result=await r.json();if(!r.ok)throw Error(result.error);cart=[];save();track('order_completed',{id:result.order_no,total:result.total});document.querySelector('#checkoutContent').innerHTML=`<div class="checkout-box"><h2>Thank you! 🌱</h2><p>Your order <b>${result.order_no}</b> has been placed. Keep this ID and use your phone/email to track it.</p><button class="btn" onclick="document.querySelector('#checkoutModal').close()">Continue shopping</button></div>`}catch(err){toast(err.message||'Could not place order. Please try again.')}};}
function toast(s){let t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
const openCart=()=>{document.querySelector('#cartDrawer').classList.add('open');document.querySelector('#overlay').classList.add('show');track('cart_opened')};document.querySelector('#cartBtn').onclick=openCart;document.querySelector('#mobileCart').onclick=openCart;document.querySelector('.close').onclick=()=>{document.querySelector('#cartDrawer').classList.remove('open');document.querySelector('#overlay').classList.remove('show')};document.querySelector('#overlay').onclick=document.querySelector('.close').onclick;document.querySelector('#searchInput').oninput=e=>{search=e.target.value;renderProducts()};document.querySelector('#categoryFilter').onchange=e=>{category=e.target.value;renderProducts()};document.querySelector('#sortSelect').onchange=e=>{sort=e.target.value;renderProducts()};document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;document.querySelector('#categoryFilter').value=category;renderProducts();location.hash='shop'});document.querySelector('#applyCoupon').onclick=()=>{coupon=document.querySelector('#coupon').value.toUpperCase();save();toast(coupon==='GREEN10'?'10% discount applied!':'Try GREEN10')};document.querySelector('#checkoutBtn').onclick=showCheckout;document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.parentElement.close());document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();track('newsletter_signup');e.target.reset();toast('Thank you for subscribing!')};document.querySelector('#trackForm').onsubmit=e=>{e.preventDefault();let id=document.querySelector('#trackId').value.toUpperCase(),c=document.querySelector('#trackContact').value,order=JSON.parse(localStorage.getItem('gpOrders')||'[]').find(o=>o.id===id&&(o.phone===c||o.email===c));document.querySelector('#trackResult').textContent=order?`Order ${order.id}: ${order.status}. Placed ${new Date(order.created).toLocaleDateString()}.`:'We could not find a matching order.';track('order_tracking',{id})};document.querySelector('.menu-btn').onclick=e=>{let nav=document.querySelector('header>nav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)};document.querySelector('#searchBtn').onclick=()=>{location.hash='shop';setTimeout(()=>document.querySelector('#searchInput').focus(),250)};document.querySelector('#mobileSearch').onclick=()=>setTimeout(()=>document.querySelector('#searchInput').focus(),350);
async function boot(){try{let r=await fetch('/api/products');if(r.ok)products=await r.json()}catch{}track('page_view',{page:'home'});renderProducts();renderCart();}
if('serviceWorker' in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));boot();
document.querySelector('#trackForm').onsubmit=async e=>{e.preventDefault();let id=document.querySelector('#trackId').value.toUpperCase(),contact=document.querySelector('#trackContact').value;try{let r=await fetch(`/api/track?order_no=${encodeURIComponent(id)}&contact=${encodeURIComponent(contact)}`),o=await r.json();document.querySelector('#trackResult').textContent=o?`Order ${o.order_no}: ${o.status}. Placed ${new Date(o.created_at).toLocaleDateString()}.`:'We could not find a matching order.'}catch{document.querySelector('#trackResult').textContent='Please start the backend first.'}};
